package br.ufes.informatica.recyclo.core.domain;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Agendamento extends PersistentObjectSupport implements Comparable<Agendamento> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@Temporal(TemporalType.TIMESTAMP)
	private Date horarioCombinado;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@Temporal(TemporalType.TIMESTAMP)
	private Date horarioDaColeta;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@Temporal(TemporalType.TIMESTAMP)
	private Date horarioCancelamento;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Gerador Source;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Coletor Source;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Oferta Target;

	/** Getter for horarioCombinado. */
	public Date getHorarioCombinado() {
		return horarioCombinado;
	}

	/** Setter for horarioCombinado. */
	public void setHorarioCombinado(Date horarioCombinado) {
		this.horarioCombinado = horarioCombinado;
	}

	/** Getter for horarioDaColeta. */
	public Date getHorarioDaColeta() {
		return horarioDaColeta;
	}

	/** Setter for horarioDaColeta. */
	public void setHorarioDaColeta(Date horarioDaColeta) {
		this.horarioDaColeta = horarioDaColeta;
	}

	/** Getter for horarioCancelamento. */
	public Date getHorarioCancelamento() {
		return horarioCancelamento;
	}

	/** Setter for horarioCancelamento. */
	public void setHorarioCancelamento(Date horarioCancelamento) {
		this.horarioCancelamento = horarioCancelamento;
	}

	/** Getter for Source. */
	public Gerador getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Gerador Source) {
		this.Source = Source;
	}

	/** Getter for Source. */
	public Coletor getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Coletor Source) {
		this.Source = Source;
	}

	/** Getter for Target. */
	public Oferta getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Oferta Target) {
		this.Target = Target;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Agendamento o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}