package br.ufes.informatica.recyclo.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Endereco extends PersistentObjectSupport implements Comparable<Endereco> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String bairro;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String logradouro;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String numero;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private complemento;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private String pontoReferencia;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private Integer cep;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Municipio Target;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne(mappedBy = "Target")
	private Usuario Source;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne(mappedBy = "Target")
	private Oferta Source;

	/** Getter for bairro. */
	public String getBairro() {
		return bairro;
	}

	/** Setter for bairro. */
	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	/** Getter for logradouro. */
	public String getLogradouro() {
		return logradouro;
	}

	/** Setter for logradouro. */
	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	/** Getter for numero. */
	public String getNumero() {
		return numero;
	}

	/** Setter for numero. */
	public void setNumero(String numero) {
		this.numero = numero;
	}

	/** Getter for complemento. */
	public  getComplemento() {
		return complemento;
	}

	/** Setter for complemento. */
	public void setComplemento( complemento) {
		this.complemento = complemento;
	}

	/** Getter for pontoReferencia. */
	public String getPontoReferencia() {
		return pontoReferencia;
	}

	/** Setter for pontoReferencia. */
	public void setPontoReferencia(String pontoReferencia) {
		this.pontoReferencia = pontoReferencia;
	}

	/** Getter for cep. */
	public Integer getCep() {
		return cep;
	}

	/** Setter for cep. */
	public void setCep(Integer cep) {
		this.cep = cep;
	}

	/** Getter for Target. */
	public Municipio getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Municipio Target) {
		this.Target = Target;
	}

	/** Getter for Source. */
	public Usuario getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Usuario Source) {
		this.Source = Source;
	}

	/** Getter for Source. */
	public Oferta getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Oferta Source) {
		this.Source = Source;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Endereco o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}