package br.ufes.informatica.recyclo.core.domain;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Endereco extends PersistentObjectSupport implements Comparable<Endereco> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	@NotNull
	private String enderecoCompleto;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String bairro;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String logradouro;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private String numero;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private String complemento;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private String pontoReferencia;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private Integer cep;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Municipio municipio;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne(mappedBy = "endereco")
	private Usuario usuario;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne(mappedBy = "endereco")
	private Oferta oferta;

	public String getEnderecoCompleto(){
		return enderecoCompleto;
	}

	public void setEnderecoCompleto(String enderecoCompleto){
		this.enderecoCompleto = enderecoCompleto;
	}

	/** Getter for bairro. */
	public String getBairro() {
		return bairro;
	}

	/** Setter for bairro. */
	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	/** Getter for logradouro. */
	public String getLogradouro() {
		return logradouro;
	}

	/** Setter for logradouro. */
	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	/** Getter for numero. */
	public String getNumero() {
		return numero;
	}

	/** Setter for numero. */
	public void setNumero(String numero) {
		this.numero = numero;
	}

	/** Getter for complemento. */
	public String getComplemento() {
		return complemento;
	}

	/** Setter for complemento. */
	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	/** Getter for pontoReferencia. */
	public String getPontoReferencia() {
		return pontoReferencia;
	}

	/** Setter for pontoReferencia. */
	public void setPontoReferencia(String pontoReferencia) {
		this.pontoReferencia = pontoReferencia;
	}

	/** Getter for cep. */
	public Integer getCep() {
		return cep;
	}

	/** Setter for cep. */
	public void setCep(Integer cep) {
		this.cep = cep;
	}

	/** Getter for municipio. */
	public Municipio getMunicipio() {
		return municipio;
	}

	/** Setter for municipio. */
	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	/** Getter for usuario. */
	public Usuario getUsuario() {
		return usuario;
	}

	/** Setter for usuario. */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	/** Getter for oferta. */
	public Oferta getOferta() {
		return oferta;
	}

	/** Setter for oferta. */
	public void setOferta(Oferta oferta) {
		this.oferta = oferta;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Endereco o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}