package br.ufes.informatica.recyclo.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.OneToMany;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Gerador extends PersistentObjectSupport implements Comparable<Gerador> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private Byte avaliacao;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "Source")
	private Set<Oferta> Target;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "Source")
	private Set<Agendamento> Target;

	/** Getter for avaliacao. */
	public Byte getAvaliacao() {
		return avaliacao;
	}

	/** Setter for avaliacao. */
	public void setAvaliacao(Byte avaliacao) {
		this.avaliacao = avaliacao;
	}

	/** Getter for Target. */
	public Set<Oferta> getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Set<Oferta> Target) {
		this.Target = Target;
	}

	/** Getter for Target. */
	public Set<Agendamento> getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Set<Agendamento> Target) {
		this.Target = Target;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Gerador o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}