package br.ufes.informatica.recyclo.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Gerador extends PersistentObjectSupport implements Comparable<Gerador> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	private Float avaliacao;
	
	@OneToOne
	private Usuario usuario;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "gerador")
	private Set<Oferta> listaOfertas;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "gerador")
	private Set<Agendamento> listaAgendamentos;

	public Float getAvaliacao() {
		return avaliacao;
	}

	public void setAvaliacao(Float avaliacao) {
		this.avaliacao = avaliacao;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	/** Getter for listaOfertas. */
	public Set<Oferta> getListaOfertas() {
		return listaOfertas;
	}

	/** Setter for listaOfertas. */
	public void setListaOfertas(Set<Oferta> listaOfertas) {
		this.listaOfertas = listaOfertas;
	}

	/** Getter for listaAgendamentos. */
	public Set<Agendamento> getListaAgendamentos() {
		return listaAgendamentos;
	}

	/** Setter for listaAgendamentos. */
	public void setListaAgendamentos(Set<Agendamento> listaAgendamentos) {
		this.listaAgendamentos = listaAgendamentos;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Gerador o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}