package br.ufes.informatica.recyclo.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Material extends PersistentObjectSupport implements Comparable<Material> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private Float taxaConversao;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 50)
	private String tipoMaterial;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany
	private Set<Oferta> Target;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany
	private Set<Coletor> Target;

	/** Getter for taxaConversao. */
	public Float getTaxaConversao() {
		return taxaConversao;
	}

	/** Setter for taxaConversao. */
	public void setTaxaConversao(Float taxaConversao) {
		this.taxaConversao = taxaConversao;
	}

	/** Getter for tipoMaterial. */
	public String getTipoMaterial() {
		return tipoMaterial;
	}

	/** Setter for tipoMaterial. */
	public void setTipoMaterial(String tipoMaterial) {
		this.tipoMaterial = tipoMaterial;
	}

	/** Getter for Target. */
	public Set<Oferta> getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Set<Oferta> Target) {
		this.Target = Target;
	}

	/** Getter for Target. */
	public Set<Coletor> getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Set<Coletor> Target) {
		this.Target = Target;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Material o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}