package br.ufes.informatica.recyclo.core.domain;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Municipio extends PersistentObjectSupport implements Comparable<Municipio> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 2)
	private String UF;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 150)
	private String nomeMunicipio;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany(mappedBy = "Target")
	private Set<Coletor> Source;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "Target")
	private Set<Endereco> Source;

	/** Getter for UF. */
	public String getUF() {
		return UF;
	}

	/** Setter for UF. */
	public void setUF(String UF) {
		this.UF = UF;
	}

	/** Getter for nomeMunicipio. */
	public String getNomeMunicipio() {
		return nomeMunicipio;
	}

	/** Setter for nomeMunicipio. */
	public void setNomeMunicipio(String nomeMunicipio) {
		this.nomeMunicipio = nomeMunicipio;
	}

	/** Getter for Source. */
	public Set<Coletor> getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Set<Coletor> Source) {
		this.Source = Source;
	}

	/** Getter for Source. */
	public Set<Endereco> getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Set<Endereco> Source) {
		this.Source = Source;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Municipio o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}