package br.ufes.informatica.recyclo.core.domain;

import java.util.Date;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Oferta extends PersistentObjectSupport implements Comparable<Oferta> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private Float qtdeMaterial;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	private Date horarioInicial;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	private Date horarioFinal;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Gerador Source;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany(mappedBy = "Target")
	private Set<Material> Source;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "Target")
	private Set<Agendamento> Source;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne
	private Endereco Target;

	/** Getter for qtdeMaterial. */
	public Float getQtdeMaterial() {
		return qtdeMaterial;
	}

	/** Setter for qtdeMaterial. */
	public void setQtdeMaterial(Float qtdeMaterial) {
		this.qtdeMaterial = qtdeMaterial;
	}

	/** Getter for horarioInicial. */
	public Date getHorarioInicial() {
		return horarioInicial;
	}

	/** Setter for horarioInicial. */
	public void setHorarioInicial(Date horarioInicial) {
		this.horarioInicial = horarioInicial;
	}

	/** Getter for horarioFinal. */
	public Date getHorarioFinal() {
		return horarioFinal;
	}

	/** Setter for horarioFinal. */
	public void setHorarioFinal(Date horarioFinal) {
		this.horarioFinal = horarioFinal;
	}

	/** Getter for Source. */
	public Gerador getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Gerador Source) {
		this.Source = Source;
	}

	/** Getter for Source. */
	public Set<Material> getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Set<Material> Source) {
		this.Source = Source;
	}

	/** Getter for Source. */
	public Set<Agendamento> getSource() {
		return Source;
	}

	/** Setter for Source. */
	public void setSource(Set<Agendamento> Source) {
		this.Source = Source;
	}

	/** Getter for Target. */
	public Endereco getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Endereco Target) {
		this.Target = Target;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Oferta o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}