package br.ufes.informatica.recyclo.core.domain;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Oferta extends PersistentObjectSupport implements Comparable<Oferta> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	@ManyToOne
	private Material material;
	
	@NotNull
	private Boolean coletado;
	
	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private Float qtdeMaterial;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	private Date horarioInicial;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	private Date horarioFinal;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Gerador gerador;


	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne(mappedBy = "oferta")
	private Agendamento agendamento;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne
	private Endereco endereco;
	

	public Material getMaterial() {
		return material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	/** Getter for qtdeMaterial. */
	public Float getQtdeMaterial() {
		return qtdeMaterial;
	}

	/** Setter for qtdeMaterial. */
	public void setQtdeMaterial(Float qtdeMaterial) {
		this.qtdeMaterial = qtdeMaterial;
	}

	/** Getter for horarioInicial. */
	public Date getHorarioInicial() {
		return horarioInicial;
	}

	/** Setter for horarioInicial. */
	public void setHorarioInicial(Date horarioInicial) {
		this.horarioInicial = horarioInicial;
	}

	/** Getter for horarioFinal. */
	public Date getHorarioFinal() {
		return horarioFinal;
	}

	/** Setter for horarioFinal. */
	public void setHorarioFinal(Date horarioFinal) {
		this.horarioFinal = horarioFinal;
	}

	/** Getter for gerador. */
	public Gerador getGerador() {
		return gerador;
	}

	/** Setter for gerador. */
	public void setGerador(Gerador gerador) {
		this.gerador = gerador;
	}

	public Agendamento getAgendamento() {
		return agendamento;
	}

	public void setAgendamento(Agendamento agendamento) {
		this.agendamento = agendamento;
	}

	/** Getter for endereco. */
	public Endereco getEndereco() {
		return endereco;
	}

	/** Setter for endereco. */
	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	public Boolean getColetado() {
		return coletado;
	}

	public void setColetado(Boolean coletado) {
		this.coletado = coletado;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Oferta o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}