package br.ufes.informatica.recyclo.core.domain;

import java.util.Date;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.OneToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Usuario extends PersistentObjectSupport implements Comparable<Usuario> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 100)
	private String email;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 30)
	private String senha;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 100)
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */

	private Float saldoCarbono;

	/** TODO: generated by FrameWeb. Should be documented. true */
	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	private Date dataCadastro;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 30)
	private String permissao;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany
	private Set<> Target;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToOne
	private Endereco Target;

	/** Getter for email. */
	public String getEmail() {
		return email;
	}

	/** Setter for email. */
	public void setEmail(String email) {
		this.email = email;
	}

	/** Getter for senha. */
	public String getSenha() {
		return senha;
	}

	/** Setter for senha. */
	public void setSenha(String senha) {
		this.senha = senha;
	}

	/** Getter for nome. */
	public String getNome() {
		return nome;
	}

	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for saldoCarbono. */
	public Float getSaldoCarbono() {
		return saldoCarbono;
	}

	/** Setter for saldoCarbono. */
	public void setSaldoCarbono(Float saldoCarbono) {
		this.saldoCarbono = saldoCarbono;
	}

	/** Getter for dataCadastro. */
	public Date getDataCadastro() {
		return dataCadastro;
	}

	/** Setter for dataCadastro. */
	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	/** Getter for permissao. */
	public String getPermissao() {
		return permissao;
	}

	/** Setter for permissao. */
	public void setPermissao(String permissao) {
		this.permissao = permissao;
	}

	/** Getter for Target. */
	public Set<> getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Set<> Target) {
		this.Target = Target;
	}

	/** Getter for Target. */
	public Endereco getTarget() {
		return Target;
	}

	/** Setter for Target. */
	public void setTarget(Endereco Target) {
		this.Target = Target;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Usuario o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}