package br.ufes.informatica.recyclo.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.recyclo.core.domain.Gerador;
import br.ufes.informatica.recyclo.core.persistence.EnderecoDAO;
import br.ufes.informatica.recyclo.core.persistence.GeradorDAO;
import br.ufes.informatica.recyclo.core.persistence.UsuarioDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class GeradorServiceBean implements GeradorService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	@EJB
	private UsuarioDAO usuarioDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private GeradorDAO geradorDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private EnderecoDAO enderecoDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public boolean incluirGerador(Gerador gerador) {
		
		// Verifica se já existe um usuário cadastrado com o e-mail informado.
		int quantidade = usuarioDAO.verificaEmailRegistrado(gerador.getUsuario());
		if (quantidade >= 1) {
			return false;
		}
	
		// Chama o usuarioDAO para armazenar as informacoes associadas à tabela Usuario.
		usuarioDAO.save(gerador.getUsuario());
		
		// Chama o geradorDAO para armzazenar as informacoes associadas à tabela Gerador.
		geradorDAO.save(gerador);
		
		// Retorna true se o gerador foi cadastrado.
		return true;
		
	}

}