package br.ufes.informatica.recyclo.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.recyclo.core.domain.Usuario;
import br.ufes.informatica.recyclo.core.persistence.UsuarioDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class LoginServiceBean implements LoginService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private UsuarioDAO usuarioDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void efetuarLogin(Usuario usuario) {
		// FIXME: auto-generated method stub
		return;
	}

}