package br.ufes.informatica.recyclo.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.recyclo.core.domain.Usuario;
import br.ufes.informatica.recyclo.core.persistence.UsuarioDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class LoginServiceBean implements LoginService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private UsuarioDAO usuarioDAO;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Usuario efetuarLogin(Usuario usuario) {
		
		// Inicializa um objeto da classe "Usuario".
		Usuario usuarioLogado;
		
		// Chama o método DAO para consultar se o usuário existe no banco de dados.
		try {
			
			// Se o usuário existe, retorna as informacoes dele.
			usuarioLogado = usuarioDAO.efetuarLogin(usuario);
			
		} catch (Exception e) {
			
			// Se o usuário não existe, retorna um objeto nulo.
			usuarioLogado = null;
			
		}
		
		// Retorno do método.
		return usuarioLogado;

		// FIXME: auto-generated method stub
		// return;
	}

}