package br.ufes.informatica.recyclo.core.application;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.recyclo.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface LoginService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Usuario efetuarLogin(Usuario usuario);

}