package br.ufes.informatica.recyclo.core.application;

import java.io.Serializable;
import java.util.Collection;

import javax.ejb.Local;

import br.ufes.informatica.recyclo.core.domain.Gerador;
import br.ufes.informatica.recyclo.core.domain.Oferta;
import br.ufes.informatica.recyclo.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface OfertaService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public void incluirOferta(Oferta oferta);

	public Collection getOfertasGerador(Usuario usuario);

}