package br.ufes.informatica.recyclo.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.recyclo.core.application.ColetorService;
import br.ufes.informatica.recyclo.core.domain.Coletor;
import br.ufes.informatica.recyclo.core.domain.Endereco;
import br.ufes.informatica.recyclo.core.domain.Municipio;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class ColetorController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private ColetorService coletorService;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private ColetorService coletorService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Coletor coletor;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Endereco endereco;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Municipio municipio;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String repeteSenha;

	/** TODO: generated by FrameWeb. Should be documented. */
	public String incluirColetor() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String alterarColetor() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String excluirColetor() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String consultarColetor() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for coletor. */
	public Coletor getColetor() {
		return coletor;
	}

	/** Setter for coletor. */
	public void setColetor(Coletor coletor) {
		this.coletor = coletor;
	}

	/** Getter for endereco. */
	public Endereco getEndereco() {
		return endereco;
	}

	/** Setter for endereco. */
	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	/** Getter for municipio. */
	public Municipio getMunicipio() {
		return municipio;
	}

	/** Setter for municipio. */
	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	/** Getter for repeteSenha. */
	public String getRepeteSenha() {
		return repeteSenha;
	}

	/** Setter for repeteSenha. */
	public void setRepeteSenha(String repeteSenha) {
		this.repeteSenha = repeteSenha;
	}

}