package br.ufes.informatica.recyclo.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.recyclo.core.application.GeradorService;
import br.ufes.informatica.recyclo.core.domain.Endereco;
import br.ufes.informatica.recyclo.core.domain.Gerador;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class GeradorController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private GeradorService geradorService;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private GeradorService geradorService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Gerador gerador;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Endereco endereco;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String repeteSenha;

	/** TODO: generated by FrameWeb. Should be documented. */
	public String incluirGerador() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String alteraGerador() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String excluirGerador() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String consultarGerador() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for gerador. */
	public Gerador getGerador() {
		return gerador;
	}

	/** Setter for gerador. */
	public void setGerador(Gerador gerador) {
		this.gerador = gerador;
	}

	/** Getter for endereco. */
	public Endereco getEndereco() {
		return endereco;
	}

	/** Setter for endereco. */
	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	/** Getter for repeteSenha. */
	public String getRepeteSenha() {
		return repeteSenha;
	}

	/** Setter for repeteSenha. */
	public void setRepeteSenha(String repeteSenha) {
		this.repeteSenha = repeteSenha;
	}

}