package br.ufes.informatica.recyclo.core.controller;

import java.util.Collection;

import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.recyclo.core.domain.Material;
import br.ufes.informatica.recyclo.core.domain.Municipio;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class MapaController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Municipio municpio;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Material tipoMaterial;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Byte tipoUsuario;

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterInfoMapa() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for municpio. */
	public Municipio getMunicpio() {
		return municpio;
	}

	/** Setter for municpio. */
	public void setMunicpio(Municipio municpio) {
		this.municpio = municpio;
	}

	/** Getter for tipoMaterial. */
	public Material getTipoMaterial() {
		return tipoMaterial;
	}

	/** Setter for tipoMaterial. */
	public void setTipoMaterial(Material tipoMaterial) {
		this.tipoMaterial = tipoMaterial;
	}

	/** Getter for tipoUsuario. */
	public Byte getTipoUsuario() {
		return tipoUsuario;
	}

	/** Setter for tipoUsuario. */
	public void setTipoUsuario(Byte tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

}