package br.ufes.informatica.recyclo.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.recyclo.core.application.OfertaService;
import br.ufes.informatica.recyclo.core.domain.Endereco;
import br.ufes.informatica.recyclo.core.domain.Gerador;
import br.ufes.informatica.recyclo.core.domain.Material;
import br.ufes.informatica.recyclo.core.domain.Oferta;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class OfertaController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private OfertaService ofertaService;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private OfertaService ofertaService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Gerador gerador;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Oferta oferta;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Material material;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Endereco endereco;

	/** TODO: generated by FrameWeb. Should be documented. */
	public void incluirOferta() {
		// FIXME: auto-generated method stub
		return;
	}

	/** Getter for gerador. */
	public Gerador getGerador() {
		return gerador;
	}

	/** Setter for gerador. */
	public void setGerador(Gerador gerador) {
		this.gerador = gerador;
	}

	/** Getter for oferta. */
	public Oferta getOferta() {
		return oferta;
	}

	/** Setter for oferta. */
	public void setOferta(Oferta oferta) {
		this.oferta = oferta;
	}

	/** Getter for material. */
	public Material getMaterial() {
		return material;
	}

	/** Setter for material. */
	public void setMaterial(Material material) {
		this.material = material;
	}

	/** Getter for endereco. */
	public Endereco getEndereco() {
		return endereco;
	}

	/** Setter for endereco. */
	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

}