package br.ufes.informatica.recyclo.core.persistence;

import java.util.Collection;
import java.util.List;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.recyclo.core.domain.Agendamento;
import br.ufes.informatica.recyclo.core.domain.Coletor;
import br.ufes.informatica.recyclo.core.domain.Gerador;
import br.ufes.informatica.recyclo.core.domain.Municipio;
import br.ufes.informatica.recyclo.core.domain.Oferta;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AgendamentoDAO extends BaseDAO<Agendamento> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterAgendasCanceladas(Municipio municipio);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterAgendasNaoRealizadas(Municipio municipio);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterAgendasRealizadas(Municipio municipio);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Agendamento realizarAgendamento(Coletor coletor, Oferta oferta);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterAgendasGerador(Gerador gerador);

	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Agendamento> obterAgendasColetor(Coletor coletor);

}