package br.ufes.informatica.recyclo.core.persistence;

import java.util.Collection;
import java.util.List;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.recyclo.core.domain.Agendamento;
import br.ufes.informatica.recyclo.core.domain.Coletor;
import br.ufes.informatica.recyclo.core.domain.Gerador;
import br.ufes.informatica.recyclo.core.domain.Municipio;
import br.ufes.informatica.recyclo.core.domain.Oferta;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class AgendamentoDAOJPA extends BaseJPADAO<Agendamento> implements AgendamentoDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Collection obterAgendasCanceladas(Municipio municipio) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Collection obterAgendasNaoRealizadas(Municipio municipio) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Collection obterAgendasRealizadas(Municipio municipio) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Agendamento realizarAgendamento(Coletor coletor, Oferta oferta) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Collection obterAgendasGerador(Gerador gerador) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List<Agendamento> obterAgendasColetor(Coletor coletor) {
		String jpql = "select a from Agendamento a where a.coletor.id = :idColetor";
		return entityManager.createQuery(jpql, Agendamento.class)
							.setParameter("idColetor", coletor.getId())
							.getResultList();	
	}

}