package br.ufes.informatica.recyclo.core.persistence;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.recyclo.core.domain.Endereco;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface EnderecoDAO extends BaseDAO<Endereco> {

}