package br.ufes.informatica.recyclo.core.persistence;

import java.util.Collection;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.recyclo.core.domain.Coletor;
import br.ufes.informatica.recyclo.core.domain.Municipio;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface MunicipioDAO extends BaseDAO<Municipio> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterMunicipiosColetor(Coletor coletor);

}