package br.ufes.informatica.recyclo.core.persistence;

import java.util.Collection;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.recyclo.core.domain.Gerador;
import br.ufes.informatica.recyclo.core.domain.Municipio;
import br.ufes.informatica.recyclo.core.domain.Oferta;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class OfertaDAOJPA extends BaseJPADAO<Oferta> implements OfertaDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Collection obterOfertasSemAgendamento(Municipio municipio) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Collection obterOfertasColetadas(Municipio municipio) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Collection obterOfertasNaoColetadas(Municipio municipio) {
		// FIXME: auto-generated method stub
		return null;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Collection obterOfertasGerador(Gerador gerador) {
		// FIXME: auto-generated method stub
		return null;
	}

}