package br.ufes.informatica.recyclo.core.persistence;

import java.util.Collection;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.recyclo.core.domain.Gerador;
import br.ufes.informatica.recyclo.core.domain.Municipio;
import br.ufes.informatica.recyclo.core.domain.Oferta;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface OfertaDAO extends BaseDAO<Oferta> {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterOfertasSemAgendamento(Municipio municipio);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterOfertasColetadas(Municipio municipio);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterOfertasNaoColetadas(Municipio municipio);

	/** TODO: generated by FrameWeb. Should be documented. */
	public Collection obterOfertasGerador(Gerador gerador);

}