package br.ufes.informatica.recyclo.core.persistence;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.recyclo.core.domain.Usuario;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class UsuarioDAOJPA extends BaseJPADAO<Usuario> implements UsuarioDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Usuario efetuarLogin(Usuario usuario) {
		String jpql = "select u from Usuario u where u.email = :email and u.senha = :senha";
		return entityManager.createQuery(jpql, Usuario.class)
							.setParameter("email", usuario.getEmail())
							.setParameter("senha", usuario.getSenha())
							.getSingleResult();
	}
	
	public int verificaEmailRegistrado(Usuario usuario) {
		String jpql = "select u from Usuario u where u.email = :email";
		int quantidade = entityManager.createQuery(jpql, Usuario.class)
				.setParameter("email", usuario.getEmail())
				.getResultList().size();
		return quantidade;
	}

}